# Generated by Django 3.1.4 on 2021-01-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=30)),
            ],
        ),
    ]
