# Generated by Django 3.1.4 on 2021-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wf_name1', models.CharField(max_length=100)),
                ('wf_icon1', models.CharField(max_length=100)),
                ('wf_description1', models.CharField(max_length=1000)),
                ('wf_name2', models.CharField(max_length=100)),
                ('wf_icon2', models.CharField(max_length=100)),
                ('wf_description2', models.CharField(max_length=1000)),
            ],
        ),
    ]
