# Generated by Django 3.1.4 on 2021-01-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='wf_icon1',
        ),
        migrations.RemoveField(
            model_name='field',
            name='wf_icon2',
        ),
        migrations.AddField(
            model_name='field',
            name='wf_description3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='field',
            name='wf_description4',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='field',
            name='wf_name3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='wf_name4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='wf_description1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='wf_description2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='field',
            name='wf_name1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='wf_name2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
