# Generated by Django 3.1.4 on 2021-01-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_auto_20210109_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='wf_description3',
        ),
        migrations.RemoveField(
            model_name='field',
            name='wf_description4',
        ),
        migrations.RemoveField(
            model_name='field',
            name='wf_name3',
        ),
        migrations.RemoveField(
            model_name='field',
            name='wf_name4',
        ),
    ]
