# Generated by Django 3.1.4 on 2021-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_auto_20210109_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('position1', models.CharField(default='', max_length=1000)),
                ('company1', models.CharField(default='', max_length=1000)),
                ('duration1', models.CharField(default='', max_length=1000)),
                ('description11', models.CharField(default='', max_length=1000)),
                ('description12', models.CharField(default='', max_length=1000)),
                ('position2', models.CharField(default='', max_length=1000)),
                ('company2', models.CharField(default='', max_length=1000)),
                ('duration2', models.CharField(default='', max_length=1000)),
                ('description21', models.CharField(default='', max_length=1000)),
                ('description22', models.CharField(default='', max_length=1000)),
                ('position3', models.CharField(default='', max_length=1000)),
                ('company3', models.CharField(default='', max_length=1000)),
                ('duration3', models.CharField(default='', max_length=1000)),
                ('description31', models.CharField(default='', max_length=1000)),
                ('description32', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
