# Generated by Django 3.1.4 on 2021-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0010_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_note',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
