# Generated by Django 3.1.4 on 2021-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0013_auto_20210109_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review1', models.CharField(default='', max_length=1000)),
                ('reviewer1', models.CharField(default='', max_length=1000)),
                ('review2', models.CharField(default='', max_length=1000)),
                ('reviewer2', models.CharField(default='', max_length=1000)),
                ('review3', models.CharField(default='', max_length=1000)),
                ('reviewer3', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
