# Generated by Django 3.1.4 on 2021-01-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='twitter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
