# Generated by Django 3.1.4 on 2021-01-09 15:04

from django.db import migrations, models
import resume_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0015_auto_20210109_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.FileField(blank=True, default='resume_app/static/images/profile.jpg', null=True, upload_to=resume_app.models.get_file_path),
        ),
    ]
