# Generated by Django 3.1.4 on 2021-01-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0016_auto_20210109_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='portfolio_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
