# Generated by Django 3.1.4 on 2021-01-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0017_resume_portfolio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=1000)),
                ('project_image', models.ImageField(upload_to='static/images/portfolio/%y')),
                ('project_url', models.CharField(default='#', max_length=1000)),
            ],
        ),
    ]
