# Generated by Django 3.1.4 on 2021-01-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0020_skilldescription_skillname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('issued_by', models.CharField(default='', max_length=1000)),
                ('certificate_url', models.CharField(default='#', max_length=1000)),
            ],
        ),
    ]
