# Generated by Django 3.1.4 on 2021-01-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0021_awards_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='awards_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='certificate_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
