# Generated by Django 3.1.4 on 2021-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0023_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='meta_des',
            field=models.CharField(default='Follow me ...', max_length=1000),
        ),
        migrations.AddField(
            model_name='metadata',
            name='meta_title',
            field=models.CharField(default='Amirul Islam', max_length=1000),
        ),
    ]
