# Generated by Django 3.1.4 on 2021-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0024_auto_20210112_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='meta_des',
            field=models.CharField(default='Follow me', max_length=1000),
        ),
    ]
