# Generated by Django 3.1.4 on 2021-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0026_userip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userip',
            old_name='created_at',
            new_name='first_visited',
        ),
        migrations.RenameField(
            model_name='userip',
            old_name='updated_at',
            new_name='last_visited',
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
